title: FSA_Counties_dd17 Geodatabase Archive
description: An archival copy and simplified version of the USDA Farm Service Agency dd17 county boundaries dataset.
author: R. Kyle Bocinsky
url: "https://climate-smart-usda.github.io/fsa-counties-dd17/"  # Your GitHub Pages URL
baseurl: ""  # Leave blank unless you're using a subdirectory
favicon: /favicon.ico
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
favicon: /favicon.ico